# Generated by Django 4.0.3 on 2022-03-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_employee_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_created',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_updated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
