# Generated by Django 4.0.3 on 2022-03-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url',
            new_name='product_url',
        ),
    ]
