# Generated by Django 4.0.3 on 2022-03-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_url_product_product_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='text',
            new_name='product_text',
        ),
    ]
