# Generated by Django 4.0.3 on 2022-03-12 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_text_product_product_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='product_category',
        ),
    ]
