# Generated by Django 4.0.3 on 2022-03-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='post_url',
        ),
    ]
