# Generated by Django 4.0.3 on 2022-03-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_url_post_post_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='post_image',
        ),
    ]
