# Generated by Django 4.0.3 on 2022-03-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_image_post_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='post_text',
        ),
    ]
