# Generated by Django 4.0.3 on 2022-03-12 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_text_post_post_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='post_category',
        ),
    ]
