# Generated by Django 4.0.3 on 2022-03-12 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_company_company_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
